---
- hosts: server
#  gather_facts: false
#  connection: local
  
  tasks:
  - name: ping test
    command: "ping -c 3 192.168.0.1"
    register: result
  - name: debug
    debug:
      msg: "{{ result.stdout }}"
      
