---
- hosts: server
  gather_facts: false
  connection: local
  
tasks:
  - name: ping test
    command: "ping -c 3 {{ inventory_hostname }}"
    register: result
  - name: debug
    debug:
      msg: "{{ result.stdout }}"
      
