---
- hosts: server
#  gather_facts: false
#  connection: local
  
  tasks:
  - name: ping test
    command: "ping 192.168.0.1 -c 3"
    register: result

  - name: debug
    debug:
      msg: "{{ result.stdout }}"
  - name: set_fact
    set_fact:
      test_fact: "TESTTEST"
